# Generated by Django 2.2.5 on 2019-09-05 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='name_text',
        ),
        migrations.AddField(
            model_name='person',
            name='firstname_text',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='lastname_text',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
