# Generated by Django 2.2.5 on 2019-09-05 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_news'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='author',
            new_name='author_text',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='content',
            new_name='content_text',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='posttime',
            new_name='posttime_text',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='team',
            new_name='team_text',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='title',
            new_name='title_text',
        ),
    ]
