# Generated by Django 2.2.5 on 2019-09-05 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_auto_20190905_1304'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='team_text',
            new_name='team',
        ),
    ]
