# Generated by Django 2.2.5 on 2019-09-05 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_auto_20190905_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='news_int',
            field=models.IntegerField(default=0),
        ),
    ]
